export const refs = {
  searchForm: document.querySelector('.search-form'),
  gallery: document.querySelector('.gallery'),
  spinner: document.querySelector('.loader'),
  gallerySet: document.querySelector('.gallery__set'),
  nightModeBtn: document.querySelector('.js-dark-theme-btn'),
  footerRef: document.querySelector('.footer'),
  signInBtn: document.querySelector('.sign-in_js'),
  closeAuthBtn: document.querySelector('[data-modal-close]'),
  authModal: document.querySelector('[data-modal]'),
  authForm: document.querySelector('#auth-form'),
  sendSignInInfo: document.querySelector('.signin__btn'),
  sendSignUpInfo: document.querySelector('.signup__btn'),
  btnLogout: document.querySelector('.log-out_js'),
  btnGoogle: document.querySelector('.google__btn'),
  authBackdrop: document.querySelector('.js-backdrop'),
  gallerySet: document.querySelector('.gallery__set'),
};
