import './js/fetchApi';
import './js/renderMarkup';
import './js/startPagStorage';
import './js/nightMode';
import './js/firebase/auth-modal-open';
import './js/firebase/firebase';
import './js/firebase/firebaseFunc';
import './js/firebase/firebaseNotifications';
import './js/spinner';
import './js/pagination';
// import './js/MyLib';
